dist: precise
language: python
cache: pip
sudo: false
env:
    - DJANGO_VERSION=1.9
    - DJANGO_VERSION=1.10
    - DJANGO_VERSION=1.11
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
script:
    - src/ci_scripts/travis.sh sqlite3 django$DJANGO_VERSION unittest
branches:
  only:
    - develop
