site_name: WireCloud
theme: readthedocs
extra_css: ['css/mkdocs.css']

pages:
- 'Introduction': 'index.md'
- 'Installation': 'installation_guide.md'
- 'Administration': 'administration_guide.md'
- 'User Guide': 'user_guide.md'
- 'Programmer Guide':
    - 'Application Mashup RESTful API': 'restapi/index.md'
    - 'Widget API': 'widgetapi/widgetapi.md'
    - 'Widget & Operator Development': 'development/widget_and_operators.md'

markdown_extensions:
    - headerid_github
    - codehilite
    - fenced_code
    - toc:
        permalink: True
        separator: "."
