site_name: WireCloud

pages:
- 'Introduction': 'index.md'
- 'Installation and Administration Guide': 'installation_and_admin_guide.md'
- 'User Guide': 'user_guide.md'
- 'Programmer Guide':
    - 'Widget API': 'widgetapi/widgetapi.md'

markdown_extensions:
    - codehilite
    - fenced_code
